version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

sphinx:
  configuration: src/bindings/python/pyPenred/docs/source/conf.py

python:
  install:
    - method: pip
      name: pyPenred  
      
    - method: pip
      path: src/bindings/python/pyPenred/docs/requirements.txt
