
materials = (
    'Hydrogen',
    'Helium',
    'Lithium',
    'Beryllium',
    'Boron',
    'Amorphous carbon',
    'Nitrogen',
    'Oxygen',
    'Fluorine',
    'Neon',
    'Sodium',
    'Magnesium',
    'Aluminium',
    'Silicon',
    'Phosphorus',
    'Sulfur',
    'Chlorine',
    'Argon',
    'Potassium',
    'Calcium',
    'Scandium',
    'Titanium',
    'Vanadium',
    'Chromium',
    'Manganese',
    'Iron',
    'Cobalt',
    'Nickel',
    'Copper',
    'Zinc',
    'Gallium',
    'Germanium',
    'Arsenic',
    'Selenium',
    'Bromine',
    'Krypton',
    'Rubidium',
    'Strontium',
    'Yttrium',
    'Zirconium',
    'Niobium',
    'Molybdenum',
    'Technetium',
    'Ruthenium',
    'Rhodium',
    'Palladium',
    'Silver',
    'Cadmium',
    'Indium',
    'Tin',
    'Antimony',
    'Tellurium',
    'Iodine',
    'Xenon',
    'Cesium',
    'Barium',
    'Lanthanum',
    'Cerium',
    'Praseodymium',
    'Neodymium',
    'Promethium',
    'Samarium',
    'Europium',
    'Gadolinium',
    'Terbium',
    'Dysprosium',
    'Holmium',
    'Erbium',
    'Thulium',
    'Ytterbium',
    'Lutetium',
    'Hafnium',
    'Tantalum',
    'Tungsten',
    'Rhenium',
    'Osmium',
    'Iridium',
    'Platinum',
    'Gold',
    'Mercury',
    'Thallium',
    'Lead',
    'Bismuth',
    'Polonium',
    'Astatine',
    'Radon',
    'Francium',
    'Radium',
    'Actinium',
    'Thorium',
    'Protactinium',
    'Uranium',
    'Neptunium',
    'Plutonium',
    'Americium',
    'Curium',
    'Berkelium',
    'Californium',
    'Einsteinium',
    'Acetone',
    'Acetylene',
    'Adenine',
    'Adipose tissue (ICRP)',
    'Air, dry (near sea level)',
    'Alanine',
    'Aluminum oxide',
    'Amber',
    'Ammonia',
    'Aniline',
    'Anthracene',
    'B-100 bone-equivalent plastic',
    'Bakelite',
    'Barium fluoride',
    'Barium sulfate',
    'Benzene',
    'Beryllium oxide',
    'Bismuth germanium oxide',
    'Blood (ICRP)',
    'Bone, compact (ICRU)',
    'Bone, cortical (ICRP)',
    'Boron carbide',
    'Boron oxide',
    'Brain (ICRP)',
    'Butane',
    'N-butyl alcohol',
    'C-552 air-equivalent plastic',
    'Cadmium telluride',
    'Cadmium tungstate',
    'Calcium carbonate',
    'Calcium fluoride',
    'Calcium oxide',
    'Calcium sulfate',
    'Calcium tungstate',
    'Carbon dioxide',
    'Carbon tetrachloride',
    'Cellulose acetate, cellophane',
    'Cellulose acetate butyrate',
    'Cellulose nitrate',
    'Ceric sulfate dosimeter solution',
    'Cesium fluoride',
    'Cesium iodide',
    'Chlorobenzene',
    'Chloroform',
    'Concrete, portland',
    'Cyclohexane',
    '1,2-dichlorobenzene',
    'Dichlorodiethyl ether',
    '1,2-dichloroethane',
    'Diethyl ether',
    'N,n-dimethyl formamide',
    'Dimethyl sulfoxide',
    'Ethane',
    'Ethyl alcohol',
    'Ethyl cellulose',
    'Ethylene',
    'Eye lens (ICRP)',
    'Ferric oxide',
    'Ferroboride',
    'Ferrous oxide',
    'Ferrous sulfate dosimeter solution',
    'Freon-12',
    'Freon-12b2',
    'Freon-13',
    'Freon-13b1',
    'Freon-13i1',
    'Gadolinium oxysulfide',
    'Gallium arsenide',
    'Gel in photographic emulsion',
    'Pyrex glass',
    'Glass, lead',
    'Glass, plate',
    'Glucose',
    'Glutamine',
    'Glycerol',
    'Graphite',
    'Guanine',
    'Gypsum, plaster of Paris',
    'N-heptane',
    'N-hexane',
    'Kapton polyimide film',
    'Lanthanum oxybromide',
    'Lanthanum oxysulfide',
    'Lead oxide',
    'Lithium amide',
    'Lithium carbonate',
    'Lithium fluoride',
    'Lithium hydride',
    'Lithium iodide',
    'Lithium oxide',
    'Lithium tetraborate',
    'Lung (ICRP)',
    'M3 wax',
    'Magnesium carbonate',
    'Magnesium fluoride',
    'Magnesium oxide',
    'Magnesium tetraborate',
    'Mercuric iodide',
    'Methane',
    'Methanol',
    'Mixed wax',
    'Ms20 tissue substitute',
    'Muscle, skeletal (ICRP)',
    'Muscle, striated (ICRU)',
    'Muscle-equivalent liquid, with sucrose',
    'Muscle-equivalent liquid, without sucrose',
    'Naphthalene',
    'Nitrobenzene',
    'Nitrous oxide',
    'Nylon, du Pont elvamide 8062',
    'Nylon, type 6 and type 6/6',
    'Nylon, type 6/10',
    'Nylon, type 11 (rilsan)',
    'Octane, liquid',
    'Paraffin wax',
    'N-pentane',
    'Photographic emulsion',
    'Plastic scintillator (vinyltoluene based)',
    'Plutonium dioxide',
    'Polyacrylonitrile',
    'Polycarbonate (makrolon, lexan)',
    'Polychlorostyrene',
    'Polyethylene',
    'Polyethylene terephthalate (mylar)',
    'Polymethyl methacrilate (lucite, perspex, plexiglass)',
    'Polyoxymethylene',
    'Polypropylene',
    'Polystyrene',
    'Polytetrafluoroethylene (teflon)',
    'Polytrifluorochloroethylene',
    'Polyvinyl acetate',
    'Polyvinyl alcohol',
    'Polyvinyl butyral',
    'Polyvinyl chloride',
    'Polyvinylidene chloride (saran)',
    'Polyvinylidene fluoride',
    'Polyvinyl pyrrolidone',
    'Potassium iodide',
    'Potassium oxide',
    'Propane',
    'Propane, liquid',
    'N-propyl alcohol',
    'Pyridine',
    'Rubber, butyl',
    'Rubber, natural',
    'Rubber, neoprene',
    'Silicon dioxide',
    'Silver bromide',
    'Silver chloride',
    'Silver halides in photographic emulsion',
    'Silver iodide',
    'Skin (ICRP)',
    'Sodium carbonate',
    'Sodium iodide',
    'Sodium monoxide',
    'Sodium nitrate',
    'Stilbene',
    'Sucrose',
    'Terphenyl',
    'Testes (ICRP)',
    'Tetrachloroethylene',
    'Thallium chloride',
    'Tissue, soft (ICRP)',
    'Tissue, soft (ICRU four-component)',
    'Tissue-equivalent gas (methane based)',
    'Tissue-equivalent gas (propane based)',
    'Tissue-equivalent plastic (A-150)',
    'Titanium dioxide',
    'Toluene',
    'Trichloroethylene',
    'Triethyl phosphate',
    'Tungsten hexafluoride',
    'Uranium dicarbide',
    'Uranium monocarbide',
    'Uranium oxide',
    'Urea',
    'Valine',
    'Viton fluoroelastomer',
    'Water, liquid',
    'Water vapour',
    'Xylene',
)
