#ifndef __PEN_ERROR_MESS__
#define __PEN_ERROR_MESS__
const char* __pen_errorMessages[] = { 
              "Success",
              "Fatal Error in PEMATR. Corrupt material data file",
              "Fatal Error in PEMATR. Too many elements in the material composition. The maximum number of elements is 30",
              "Fatal Error in PEMATR. Too many oscillators.",
              "Fatal Error in PEMATR. Inconsistent oscillator data.",
              "Fatal Error in PEMATR. Too many shells",
              "Fatal Error in PEMATR. Too many data points (1).",
              "Fatal Error in PEMATR. PHMART. No outer shells?",
              "Fatal Error in PEMATR. Too many data points (2).",
              "Fatal Error in RELAXR. NTRAN needs to be increased.",
              "Fatal Error in RELAXR. Insufficient memory storage.",
              "Fatal Error in RELAXR. Negative transition probability?",
              "Fatal Error in RELAXR. Rounding error is too large.",
              "Fatal Error in PSIaR. Corrupt material data file.",
              "Fatal Error in PSIaR. Too many data points.",
              "Fatal Error in PSIaR. Too many shells.",
              "Fatal Error in PSIaR. Insufficient memory storage.",
              "Fatal Error in EBRaR. EBRR. Inconsistent format.",
              "Fatal Error in SINTEG. Integral limits out of range.",
              "Fatal Error in material load. No context assigned to material.",
              "Fatal Error in material load. Corrupted context.",
              "Fatal Error in BRAR. Inconsistent data",
              "Fatal Error in BRAR. Corrupt data file (pdbrang.p08).",
              "Fatal Error in SPLINE: N is less than 4",
              "Fatal Error in SPLINE: X values not in increasing order",
              "Fatal Error in DCSEL. Energy out of range",
              "Fatal Error in RLMOM. Error code 0",
              "Fatal Error in RLMOM. Error code 1",
              "Fatal Error in RLMOM. Error code 2",
              "Fatal Error in RLMOM. Error code 3",
              "Fatal Error in RLMOM. Error code 4",
              "Fatal Error in EELa0. Negative total cross section",
              "Fatal Error in EELa0. Inconsistent arguments",
              "Fatal Error in EELdR. Error reading electron elastic DCS data",
              "Fatal Error in EELdR. Electron cross section data are corrupt",
              "Fatal Error in EELdR. Error reading positron elastic DCS data",
              "Fatal Error in EELdR. Positron cross section data are corrupt",
              "Fatal Error in RMOMX. Error code 1",
              "Fatal Error in RMOMX. Error code 2",
              "Fatal Error in RMOMX. Error code 3",
              "Fatal Error in RMOMX. Error code 4",
              "Fatal Error in RITAI0: N must be larger than 8",
              "Fatal Error in RITAI0: N must be less than NM512",
              "Fatal Error in RITAI0: XLOW must be larger than XHIGH",
              "Fatal Error in RITAI0: XLOW and NU are negative",
              "Fatal Error in EGRID: The energy interval is too narrow",
              "Fatal Error in GPHaR. Corrupt material data file",
              "Fatal Error in GPHaR. Too many data points",
              "Fatal Error in GPHaR. Too many shells",
              "Fatal Error in GPHaR. Insufficient memory storage",
              "Fatal Error in MERGE2. Increase the value of the parameter NP",
              "Fatal Error in SORT2. Increase the value of the parameter NP",
              "Fatal Error in ELINIT. Corrupt data file",
              "Fatal Error in ESIaR. Corrupt material data file",
              "Fatal Error in ESIaR. Too many data points",
              "Fatal Error in ESIaR. Too many shells",
              "Fatal Error in ESIaR. Insufficient memory storage",
              "Fatal Error in GRAaR. RITA initialisation error",
              "Fatal Error in GRAaR. RITA interpolation error is too large",
              "Fatal Error int SLAG6: too few data points",
              "Fatal Error in IRND0. Negative point probability",
              "Fatal Error in RNDG30: initialisation error (1)",
              "Fatal Error in RNDG30: initialisation error (2)",
              "Warning: particle stack is full",
              "Fatal Error in PEINIT: Electron absorption energy less than 50 eV.",
              "Fatal Error in PEINIT: Photon absorption energy less than 50 eV.",
              "Fatal Error in PEINIT: Positron absorption energy less than 50 eV.",
              "Fatal Error in PEINIT: The energy interval is too narrow",
              "Fatal Error in PEINIT: Too many materials. Edit 'pen_constants.hh' and change MAXMAT parameter",
              "Fatal Error in PEINIT: The material data file could not be opened",
              "Last error."};
#endif
