name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Build check
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            release_suffix: ubuntu
          - os: windows-latest
            release_suffix: windows            
          - os: macos-latest
            release_suffix: mac
    runs-on: ${{matrix.os}}
            
    steps:
    - uses: actions/checkout@v2

    - name: Create building folder
      run: |
        mkdir ${{ github.workspace }}/src/build

    - name: Build and compile
      run: |
        cmake -DWITH_DICOM="OFF" -DWITH_MULTI_THREADING="ON" -DWITH_MPI="OFF" -DWITH_LB="OFF" -DDEVELOPMENT_WARNINGS="ON" ../
        cmake --build . --config Release --target install
      working-directory: ${{ github.workspace }}/src/build
              
    - name: Print PenRed version
      run: |
        ./pen_main --version
      working-directory: ${{ github.workspace }}/src/compiled/mains/penmain

    - name: Print PenRed registered tallies
      run: |
        ./regTallies
      working-directory: ${{ github.workspace }}/src/compiled/registers
      
    - name: Print PenRed registered geometries
      run: |
        ./regGeometries
      working-directory: ${{ github.workspace }}/src/compiled/registers
      
    - name: Print PenRed registered particle samplers
      run: |
        ./regSamplers
      working-directory: ${{ github.workspace }}/src/compiled/registers
