name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:

    name: ${{matrix.name}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
          os: [ubuntu-latest,windows-latest]
          name: [Ubuntu,Windows]
            
    steps:
    - uses: actions/checkout@v2

    - name: Create building folder
      run: |
        mkdir ${{ github.workspace }}/src/build

    - name: Configure and build cmake
      run: |
        cmake -DWITH_DICOM="OFF" -DWITH_MULTI_THREADING="ON" -DWITH_MPI="OFF" -DWITH_LB="OFF" -DDEVELOPMENT_WARNINGS="ON" ../
      working-directory: ${{ github.workspace }}/src/build
      
    - name: Compile the code 
      run: |
        make install
      working-directory: ${{ github.workspace }}/src/build
        
    - name: Print PenRed version in unix environment
      if: runner.os != 'Windows'
      run: |
        ./pen_main --version
      working-directory: ${{ github.workspace }}/src/compiled/mains/penmain

    - name: Print PenRed version in windows environment
      if: runner.os == 'Windows'
      run: |
        .\pen_main --version
      working-directory: ${{ github.workspace }}/src/compiled/mains/penmain
