name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:

    name: ${{matrix.name}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
          os: [ubuntu-latest,windows-latest]
          name: [Ubuntu,Windows]
            
    steps:
    - uses: actions/checkout@v2

    - name: Create building folder
      run: |
        mkdir ${{ github.workspace }}/src/build

    - name: Configure and build cmake
      run: |
        cd ${{ github.workspace }}/src/build
        cmake -DWITH_DICOM="OFF" -DWITH_MULTI_THREADING="ON" -DWITH_MPI="OFF" -DWITH_LB="OFF" -DDEVELOPMENT_WARNINGS="ON" ../
        
    - name: Compile the code 
      run: |
        cd ${{ github.workspace }}/src/build
        make install
        
    - name: Print PenRed version
      run: |
        cd ${{ github.workspace }}/src/build/compiled/mains/penmain
        ./pen_main --version
