name: Deploy Documentation
on:
  push:
    branches:
      - v-1.13.0
  workflow_dispatch:  # Allow manual triggering of the workflow

# Grant permissions for the workflow to deploy to GitHub Pages
permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v4

      # Set up Python
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      # Install MkDocs, Material theme, and PyMdown extensions
      - run: pip install mkdocs mkdocs-material pymdown-extensions

      # Build the documentation
      - run: cd src/utilities/Blender/4.2.3/mkdocs && mkdocs build --site-dir ./site

      # Upload the built documentation as a GitHub Pages artifact
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./src/utilities/Blender/4.2.3/mkdocs/site

  deploy-pages:
    needs: deploy  # Wait for the deploy job to complete
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      # Deploy the artifact to GitHub Pages
      - uses: actions/deploy-pages@v4
